name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-lateststeps:
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
